type User {
    id: ID!
    userName: String!
}

type Post {
    id: ID!
    authorId: Int!
    content: String!
    creationTime: String!
}

type Comment{
    id: ID!
    authorId: Int!
    postId: Int!
    content: String!
    creationTime: String!
}

type Query{
    users: [User!]!
    posts: [Post!]!
    comments: [Comment!]!
    getUser(id: ID!): User
    getPost(id: ID!): Post
    getComment(id: ID!): Comment
}

input UserCreateRequest{
    userName: String!
}

input PostCreateRequest{
    authorId: Int!
    content: String!
    creationTime: String
}

input CommentCreateRequest{
    authorId: Int!
    postId: Int!
    content: String!
    creationTime: String
}

type Mutation{
    createUser(request: UserCreateRequest!): User!
    createPost(request: PostCreateRequest!): Post!
    createComment(request: CommentCreateRequest!): Comment!
}




